
services:
  database:
    image: mariadb:11
    environment: 
      MARIADB_ROOT_PASSWORD: root 
      MARIADB_DATABASE: blogtech 
      MARIADB_USER: symfony 
      MARIADB_PASSWORD: symfony 
    volumes: 
      - carole_blogtech_db_data:/var/lib/mysql 
    ports: 
      - "3307:3307" 
volumes: 
  carole_blogtech_db_data:
